name: Update Weather Cache

on:
  schedule:
    # 毎時17分に実行（ジャストタイム回避）
    - cron: '17 * * * *'
  workflow_dispatch: # GitHub画面から手動実行テストを可能にする設定

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cron Endpoint
        run: |
          curl -s -X GET "https://fishing-weather-bot.onrender.com/cron_trigger"
